### ISSUE TITLE
Bug: 移动端下菜单按钮点击无效

### ISSUE THREAD

**Issue by neveler** [koishijs/webui#107]
### Describe the bug

Bug: 移动端下菜单按钮点击无效

### Steps to reproduce

略

### Expected behavior

点击后应出现菜单

### Screenshots

![image](https://user-images.githubusercontent.com/55753029/220654732-7f73cd5b-13bd-455f-87b3-f7a34a9b73fa.png)

### Versions

- Koishi version: latest

**Comment by shigma** [comment]
![54eac2a2f57e28e4284fed855e7e4f43](https://user-images.githubusercontent.com/33423008/220830630-d881a203-b673-4142-89d6-504a4fca7729.jpg)

我这里一切正常，推测是设备问题，请提供你的设备信息。

**Comment by shigma** [comment]
![Uploading image.png…]()

依然没有复现。
