### ISSUE TITLE
Feature: 插件市场插件卡片中添加最后更新时间显示

### ISSUE THREAD

**Issue by Discreater** [koishijs/webui#111]
目前虽然可以按更新时间排序，但是看不到具体的时间。

或许可以添加到卡片中的这个位置:
![AXG JARA$ALK0X@UYL_MSE9](https://user-images.githubusercontent.com/41231596/220903288-4576069b-214f-4221-b39f-464b950a59e7.png)

**Comment by shigma** [comment]
已支持功能，现在做到了版本号的 tooltip 上面。
