### ISSUE TITLE
Feature: 一键更新插件

### ISSUE THREAD

**Issue by PSR2144-3933** [koishijs/webui#115]
### Describe the problem related to the feature request

对于使用了一大堆插件的用户来说，一个一个点插件更新可能会把手指点断(

### Describe the solution you'd like

在依赖管理页面增加一个按钮来一键更新所有插件

**Comment by Lipraty** [comment]
建议添加一下 issue 的标题（

**Comment by PSR2144-3933** [comment]
> 建议添加一下 issue 的标题（

加了(

**Comment by shigma** [comment]
这需求挺好的，可以做。

**Comment by itzdrli** [comment]
没几个插件光是yarn create出来的模板里自带插件更新一次手都得费（

**Comment by shigma** [comment]
已经加入 4.12 Roadmap。
