### ISSUE TITLE
Feature: 返回插件市场界面时保留滚动进度

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/webui#118]
![image](https://user-images.githubusercontent.com/21092951/222990405-0df096d3-0e4a-4966-a53b-ae188546bda1.png)

用全新安装测试过，的确有此问题

**Comment by shigma** [comment]
离开界面自然是解决不了的……页面都关掉了怎么保存进度？

**Comment by shigma** [comment]
由于目前插件市场已经有分页，因此此 issue 已无需实现。

相关：https://github.com/koishijs/webui/issues/170
