### ISSUE TITLE
Bug: 「前往指令」按钮非响应式

### ISSUE THREAD

**Issue by ilharp** [koishijs/webui#120]
### Describe the bug

「前往指令」按钮不会根据当前条目是否为指令而显示或隐藏。

在非指令条目点击按钮会前往最后一次被选择的指令。

### Steps to reproduce

打开「本地化」页面，点击任意指令条目后点击 general

### Expected behavior

根据当前条目是否为指令而显示或隐藏。

### Screenshots

![image](https://user-images.githubusercontent.com/20179549/223216034-47ca740c-2f6c-43b0-960b-5a29d7577778.png)

### Versions

```txt
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

Binaries:
    Node: 16.17.0
    Yarn: 3.2.3

Koishi:
    Core: 4.11.9
    Console: 5.5.3
    Koishi Desktop: 0.9.2
```

**Comment by shigma** [comment]
已修复，请更新 @koishijs/plugin-console 到最新版本。
