### ISSUE TITLE
Feature: 让DataView可以翻页

### ISSUE THREAD

**Issue by MetaSorcerer** [koishijs/webui#129]
### Describe the problem related to the feature request

dialogue里面问答比较多，想通过数据库查看，但是数据库只显示了第一页，还没法翻页，因此求增加翻页功能

### Describe the solution you'd like

可以翻页，如果可以的话dialogue里面有的回答特别长，但是在dataview里面显示都是单行，不太直观，希望可以双击单元格以后视图上可以展开看

**Comment by shigma** [comment]
这个是不是已经实现了（
