### ISSUE TITLE
Feature: 移动端的侧边栏按钮旁显示标题

### ISSUE THREAD

**Issue by idanran** [koishijs/webui#131]
由于移动端不容易将光标悬停在按钮上，（移动端）直接在按钮旁显示文字应该会更好。

**Comment by shigma** [comment]
Koishi 这里参考 discord 设计，discord 的移动端左侧没有提示文字，只有按钮。

**Comment by idanran** [comment]
> Koishi 这里参考 discord 设计，discord 的移动端左侧没有提示文字，只有按钮。

嗷
