### ISSUE TITLE
Bug: 多实例时关闭status导致整个console被同化

### ISSUE THREAD

**Issue by medicago087** [koishijs/webui#133]
![image](https://user-images.githubusercontent.com/68104673/226261921-96cb6819-4bd5-4553-8b0f-e965fde0174c.png)
这是正常状态
![image](https://user-images.githubusercontent.com/68104673/226261977-15788816-cb9c-4c86-91b0-7f7d24d59ff5.png)
此时我们关闭default的status并刷新
![image](https://user-images.githubusercontent.com/68104673/226262086-0830e3c7-21e6-428d-b8cc-32d792d8f9d2.png)
好！复制人！

**Comment by medicago087** [comment]
并且停止default2后刷新default1恢复原console

**Comment by shigma** [comment]
好怪啊，我感觉不是单纯某个插件导致的

cc @ilharp

**Comment by ilharp** [comment]
我前几天就看到了，但我一直觉得可能会是多实例忘记改端口，或者之类的

你可以按照下面的步骤排查一下：

1. 按照下图的「Koishi 图标 - 高级 - 打开终端」打开 Koishi 桌面终端
2. 然后输入 `koi ps`

![image](https://user-images.githubusercontent.com/20179549/226387998-aeb20ada-2b82-41e1-80db-caf6793539a7.png)

**Comment by MirrorCY** [comment]
这个问题我上次上去看过，确实没有修改端口，修改端口后正常

大概是 Koishi 检测到端口冲突成功自增了，但是 KD 启动的窗口依旧是按照 koishi.yml 内填写的端口
感觉可以在 KD 解决这个问题，启动完成一个 Koishi 实例再依次启动下一个，这样就可以判断自增后的端口号了

**Comment by medicago087** [comment]
端口相同时稳定复现，端口不同时复现不了，可以确认是端口导致的，但为什么status的开关会影响KD启动窗口的端口获取，我依然打个问号

**Comment by ilharp** [comment]
Koishi Desktop 获取的是这一条日志中的端口：

```
[I] app server listening at http://127.0.0.1:5140
```

![image](https://user-images.githubusercontent.com/20179549/229766922-7fd3c9a8-cb0c-46f8-9edc-5af85e8bc62f.png)

就结果上来看，两个窗口确实打开的都是开放端口 5140 的实例，这导致你开关的实际上是同一个实例的插件。这可能是导致最终问题的原因。

---

此外，Koishi 有一个“正常现象”，就是在窗口内修改了端口后，当前窗口不会更换到新地址。这个现象是理所应当的；如果更换了端口，那么需要使用右下角的「打开」按钮打开一个新的窗口即可解决。

**Comment by shigma** [comment]
@ilharp 你的意思是说第二个实例实际上监听了 5141 但是输出的日志有误吗？

**Comment by MaikoTan** [comment]
I assuming this is the bug from Koishi itself.

On my testbench, when I have multiple Koishi instances running, the second one prints out `[I] app server listening at http://0.0.0.0:3000/` (I am using 3000 port for every instances), but I didn't see there are any ports that the instance listening. The only 3000 port listened by `node` was the first instance.
