### ISSUE TITLE
Feature: market增强显示

### ISSUE THREAD

**Issue by medicago087** [koishijs/webui#135]
### Describe the problem related to the feature request

![image](https://user-images.githubusercontent.com/68104673/227452615-48da6cda-2344-4c7c-bc01-9955edbd956f.png)
![image](https://user-images.githubusercontent.com/68104673/227453539-305c7b61-388c-47f7-a3f3-6a2289b901a2.png)
用户群遇到的问题：“你尚未配置此插件，点击立即配置”中点击哪里不明晰。特别是安卓，无法看到鼠标移过显示的下划线。

### Describe the solution you'd like

建议更改“点击”为蓝色或者其他方案，增加辨识度。

**Comment by shigma** [comment]
增加了「插件配置管理」功能。

如果插件同时存在多份配置，则在插件的详情页中出现配置管理提示。点击后将弹出对话框，用户可以在其中查看和跳转到所有配置，也可以删除或添加配置。

![image](https://github.com/koishijs/webui/assets/33423008/b5b59b60-af47-403c-91ef-41df8686c7cc)

当查看已经安装到本地的插件时，会新增「配置」按钮。点击后：

- 如果该插件尚未被配置，则立即在顶层创建一份配置并跳转；
- 如果该插件仅存在一份配置，则立即跳转到该配置页面；
- 如果该插件同时存在多份配置，则会打开上述配置管理页面，允许用户进行选择。

![image](https://github.com/koishijs/webui/assets/33423008/e2c93acb-54ce-455c-9ec2-4826e0164ed6)

此外，插件安装成功后，也会按照相同的逻辑创建、跳转或弹出配置管理界面。
