### ISSUE TITLE
Feature: 在插件设置页按下 Ctrl+S 时保存插件配置而不是下载网页

### ISSUE THREAD

**Issue by MicroCBer** [koishijs/webui#142]
### Describe the problem related to the feature request

按下 Ctrl + S 会保存网页而不是保存配置，很不符合直觉

### Describe the solution you'd like

在插件设置页按下 Ctrl+S 时保存插件配置而不是下载网页

**Comment by ilharp** [comment]
控制台键盘快捷键可以作为一个大的功能项做，包括 ⌘S 保存、⌘D 克隆、Del 删除、⌘C/⌘V 复制粘贴等等。

**Comment by shigma** [comment]
> 控制台键盘快捷键可以作为一个大的功能项做，包括 ⌘S 保存、⌘D 克隆、Del 删除、⌘C/⌘V 复制粘贴等等。

是的，可能在未来提供以下的功能：

1. 将控制台的各种操作抽象成为可以注册的 action，例如保存配置 / 重载插件
2. 将控制台的各种状态抽象成为一个可描述的对象，例如 route, activity 等等
3. 允许注册键盘快捷键，包括状态、输入、行为，例如在插件配置页面、输入 ⌘S、执行 1 中操作
4. 提供一个专门的页面，允许用户配置快捷键
5. 将快捷键与标题栏菜单、右键菜单整合起来

**Comment by shigma** [comment]
已经支持 Ctrl+S 保存。
