### ISSUE TITLE
Bug: dev模式下设置一个名为`test`的指令会导致日志中出现一个数组

### ISSUE THREAD

**Issue by ifrvn** [koishijs/webui#148]
只要`ctx.command('test')`就行

![image](https://user-images.githubusercontent.com/21982381/231046651-b054cf8c-ea0e-49be-9cf1-20b53e835499.png)

原因在

https://github.com/koishijs/webui/blob/fa831fed7225974dffaf2d0930609e40e054ee9b/packages/commands/src/service.ts#L109

这是故意的还是不小心（

**Comment by shigma** [comment]
我们删除了大部分的调试代码，但我们保留了一小部分。我认为只有保留了一部分，你才知道你用的是 Koishi（狗头）
