### ISSUE TITLE
bug(sandbox): context menu couldn't be closed

### ISSUE THREAD

**Issue by ifrvn** [koishijs/webui#153]
![L91)57GQTV3_`_BQSK9MNL0](https://user-images.githubusercontent.com/21982381/232693891-7927362b-b993-4e47-a901-efc0d55ad008.png)

context menu of sandbox cannot be closed by clicking other place unless you click one of the menus or refresh the page.

versions:
- koishi : 4.12.5
- sandbox : 3.1.0

**Comment by ifrvn** [comment]
悲报，更新sandbox3.1.1后右键菜单出不来了

**Comment by shigma** [comment]
blame @MaikoTan
