### ISSUE TITLE
Bug: 当插件当前版本大于插件市场的最新版本时获取插件信息会无法加载

### ISSUE THREAD

**Issue by zhuhansan666** [koishijs/webui#164]
## 当插件当前版本大于插件市场的最新版本时获取插件信息会无法加载

![error](https://github.com/koishijs/webui/assets/93586645/f7e3c57b-158c-4807-a8dd-079a4e2bb976)

**Comment by zhuhansan666** [comment]
这是日志
[2023-05-15.log](https://github.com/koishijs/webui/files/11486433/2023-05-15.log)

**Comment by shigma** [comment]
看控制台报错，F12

**Comment by zhuhansan666** [comment]
目前暂时无条件复现，设置环境较为麻烦

**Comment by Chinese-Cyq20100313** [comment]
手动改一下package.json很难吗（

**Comment by Chinese-Cyq20100313** [comment]
> 目前暂时无条件复现，设置环境较为麻烦

手动改一下package.json很难吗（

**Comment by zhuhansan666** [comment]
好了，catch到log了
[192.168.1.1-1684238197662.log](https://github.com/koishijs/webui/files/11487524/192.168.1.1-1684238197662.log)

**Comment by shigma** [comment]
<img width="650" alt="image" src="https://github.com/koishijs/webui/assets/33423008/d207623c-54c7-4a1c-9c3d-1e3394e45426">

看了下报错信息，有两个：

- 第一个报错似乎跟这个问题无关，但跟你的依赖版本有关，如果你是开发环境，或许应该留意一下 @vueuse/core 这个依赖是否多例了
- 第二个报错我暂时无法定位，建议把这个报错定位信息给到（F12 到报错位置然后 formatted 给上下 10 行以上的文件截图）

**Comment by zhuhansan666** [comment]
![image](https://github.com/koishijs/webui/assets/93586645/3d1ead5b-905c-4b56-8497-d35c154e6d57)

**Comment by shigma** [comment]
> ![image](https://user-images.githubusercontent.com/93586645/238640220-3d1ead5b-905c-4b56-8497-d35c154e6d57.png)

这个问题我应该修过了，现在最新版还有 issue 中提及的问题吗？

**Comment by shigma** [comment]
已修复
