### ISSUE TITLE
某些组件会在移动端占用过大的面积

### ISSUE THREAD

**Issue by idanran** [koishijs/webui#175]
![Screenshot_2023-05-27-13-30-01-12_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/koishijs/webui/assets/96647698/8d3a0847-adfd-4a06-b486-e58da3da31f1)

包含「添加用户」的那一部分。

**Comment by ilharp** [comment]
这是预期的行为。宽菜单在移动设备上的设计行为就是占满屏幕，并保留右侧若干像素用于退出。

如果你有更好的设计建议的话可以提出，但必须使活动栏、左侧菜单和主布局三个组件均可在任意状态下的一次切换内显示。

**Comment by idanran** [comment]
> 这是预期的行为。宽菜单在移动设备上的设计行为就是占满屏幕，并保留右侧若干像素用于退出。
> 
> 如果你有更好的设计建议的话可以提出，但必须使活动栏、左侧菜单和主布局三个组件均可在任意状态下的一次切换内显示。
> 

感觉用于退出的部分太小。

**Comment by ilharp** [comment]
> > 这是预期的行为。宽菜单在移动设备上的设计行为就是占满屏幕，并保留右侧若干像素用于退出。
> > 如果你有更好的设计建议的话可以提出，但必须使活动栏、左侧菜单和主布局三个组件均可在任意状态下的一次切换内显示。
> 
> 感觉用于退出的部分太小。

确实存在此问题。不过增大退出部分的宽度则会减少菜单的宽度，这里需要有更好的布局设计方案解决此问题。

**Comment by shigma** [comment]
可以优化一下。

**Comment by idanran** [comment]
好欸
