### ISSUE TITLE
Bug: WebUi移动端无法通过点击返回上一级菜单

### ISSUE THREAD

**Issue by BERADQ** [koishijs/webui#182]
### Describe the bug

通过左上角打开了二级菜单，我再点击右侧并无法返回/收起二级菜单。

### Steps to reproduce

使用最新的console和client

### Expected behavior

点击菜单外的区域应该返回/收起菜单

### Screenshots

![IMG_6176](https://github.com/koishijs/koishi/assets/78293733/23786221-d0f5-4f7c-a9b8-b5f9741fde5d)

### Versions

- OS: iOS 16
- Platform: Safari
- Node version: 20
- Koishi version: 4.13.1
- plugin-console version: 5.10.2

### Additional context

怎么加了个menu，改了个settings，就多了这些bug…感觉这些东西没什么影响啊🤔️

**Comment by shigma** [comment]
主要问题在于重构了主题系统，挪了一些文件导致相关的 CSS 失效了。

非常抱歉，问题现已修复。
