### ISSUE TITLE
Bug: 依赖管理不能正确检查依赖更新

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/webui#189]
### Describe the bug

当某个依赖/插件版本更新时，点击右上角刷新按钮，依赖管理中无任何更新
对于更新的是插件的场合：商店可以正常刷新且更新的插件版本显示正常
停用market再重新启用后正常

### Steps to reproduce

/

### Expected behavior

可以正常检查更新

### Screenshots

![image](https://github.com/koishijs/koishi/assets/16983883/5b0f5b4b-7db4-41c5-b0dd-e6fea2832b9a)
![image](https://github.com/koishijs/koishi/assets/16983883/b8d69607-d8bc-45f8-84c6-b9beafa48679)

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by Chinese-Cyq20100313** [comment]
有这种情况，registry 里早就更新了但是market和deps都刷不出来的问题
也许和 #184 有关？

**Comment by shigma** [comment]
本 issue 已复现。将尽快修复。

#184 应该是另外的问题。

**Comment by Hieuzest** [comment]
![image](https://github.com/koishijs/webui/assets/16983883/0ff5f30c-34c0-4de3-a120-e4c5fc7ec13a)
后续。本地版本一栏没有正常更新。

**Comment by shigma** [comment]
> ![image](https://user-images.githubusercontent.com/16983883/248568569-0ff5f30c-34c0-4de3-a120-e4c5fc7ec13a.png) 后续。本地版本一栏没有正常更新，看起来是一点小小的绑定问题。

草，太怪了，我看了半天也没看出代码有什么问题。

**Comment by shigma** [comment]
试试最新版本，应该修了。
