### ISSUE TITLE
BUG：sandbox中&被转换成&amp;传递到command参数中

### ISSUE THREAD

**Issue by HuanLinOTO** [koishijs/webui#195]
~~标题不太顺，但是看图就懂了~~

![Cache_-6ea4c24b3e13113f](https://github.com/koishijs/webui/assets/94176676/4ba26a4e-80a7-472d-b935-49e401c7c0da)

参数标注为text，报错来自别的地方

**Comment by CyanChanges** [comment]
![image](https://github.com/koishijs/webui/assets/68551684/b2ddd6fe-220b-441e-9310-c37bbebf07c0)
https://github.com/koishijs/webui/blob/main/plugins/sandbox/client/layout.vue#L149

然后发送消息，直接发送给后端

![image](https://github.com/koishijs/webui/assets/68551684/d4265d42-f855-4f40-a9ed-d0ba23ddd9f8)
https://github.com/koishijs/webui/blob/main/plugins/sandbox/src/index.ts#L93
这边也没有 unescape, 然后就这么收到了未 unescape 过的消息

**Comment by HuanLinOTO** [comment]
还有一点是，↑ ↓ 键切换上下文中也有这个问题

**Comment by CyanChanges** [comment]
![image](https://github.com/koishijs/webui/assets/68551684/d9208368-9faf-4599-bd7f-da6aefe503f0)
https://github.com/koishijs/webui/blob/main/plugins/sandbox/src/index.ts#L100

继之前，后端收到消息 (未 unescape) 之后会发送一个 sandbox/message 给前端

![image](https://github.com/koishijs/webui/assets/68551684/7241f12d-1101-47b3-8e2a-ce2c5ca25edf)
https://github.com/koishijs/webui/blob/main/plugins/sandbox/client/utils.ts#L40

前端接收到消息之后就会把存储消息 (未 unescape) 到 @koishijs/client 的存储 (useLocalStorage of @vueuse/core)

![image](https://github.com/koishijs/webui/assets/68551684/69f24aaf-de6b-4428-97c2-37ba7c2ba685)
https://github.com/koishijs/webui/blob/main/plugins/sandbox/client/layout.vue#L111

当你使用上下切换之前的消息时，读取存储的消息 (未 unescape)，于是你就会看到：
你输入的 &amp; (还有其他被 escape 的字符) 全变成 &amp;amp; 了
由于 &amp;amp; 中也有 &amp;  
你可以继续 发送(Enter)，上一个(UpArrow)，无限循环，这个消息长度就会一直增加 (
![image](https://github.com/koishijs/webui/assets/68551684/58c71340-345a-4e7e-bf32-9f847748bb1d)

**Comment by CyanChanges** [comment]
pr 了 #197

**Comment by CyanChanges** [comment]
emmm 是不是有点久

**Comment by CyanChanges** [comment]
好了速通了【速通 Koishi！-哔哩哔哩】 https://b23.tv/v9c6AYL

**Comment by CyanChanges** [comment]
6，终于修了

**Comment by shigma** [comment]
这个问题可以被拆分为两个问题：

1. 按下 ↑ 时的错误转义
2. text 类型没有被反转义

后一个问题将会在 koishi 仓库中修复。
