### ISSUE TITLE
Bug: 控制台会将 Win11 识别成 Win10

### ISSUE THREAD

**Issue by idanran** [koishijs/webui#196]
![Screenshot 2023-07-04 203505](https://github.com/koishijs/webui/assets/96647698/f3bbb756-70f7-4556-86e1-c6fdc24b888f)

![image](https://github.com/koishijs/webui/assets/96647698/83f59d4c-f1ad-4f11-b0d1-f8fceacf4fc7)

**Comment by ilharp** [comment]
Blocked by upstream: https://github.com/tabrindle/envinfo/issues/209

**Comment by idanran** [comment]
> Blocked by upstream: [tabrindle/envinfo#209](https://github.com/tabrindle/envinfo/issues/209)

问题可能出在它的上游：
https://github.com/tabrindle/envinfo/blob/cbdd2048ea919222e4f935e82ece2a265dddd816/src/helpers/system.js#L56C1-L56C1 
https://github.com/sindresorhus/os-name

**Comment by CyanChanges** [comment]
你说的对，但是 Windows 11 还是 Windows NT 10.0

**Comment by ilharp** [comment]
> 你说的对，但是 Windows 11 还是 Windows NT 10.0

你书得对，但是 Windows 7 是 Windows NT 6.1（

**Comment by CyanChanges** [comment]
> > 你说的对，但是 Windows 11 还是 Windows NT 10.0
> 
> 你书得对，但是 Windows 7 是 Windows NT 6.1（

你说的对但是 cmd 都说这是 Win10（

**Comment by ilharp** [comment]
> > > 你说的对，但是 Windows 11 还是 Windows NT 10.0
> > 
> > 
> > 你书得对，但是 Windows 7 是 Windows NT 6.1（
> 
> 你说的对但是 cmd 都说这是 Win10（

你书得对，但是 Windows 7 确实被显示成了 Windows 7，如果你觉得这是 bug 那么可以给上游开一个 Issue

**Comment by CyanChanges** [comment]
> > > > 你说的对，但是 Windows 11 还是 Windows NT 10.0
> > > 
> > > 
> > > 你书得对，但是 Windows 7 是 Windows NT 6.1（
> > 
> > 
> > 你说的对但是 cmd 都说这是 Win10（
> 
> 你书得对，但是 Windows 7 确实被显示成了 Windows 7
> 
> 如果你觉得显示成 Windows 7 是一个 bug，那么可以给上游开一个 Issue
> 
> 如果你觉得显示成 6.1 是一个 bug，那么可以给微软开一个 Issue
> 
> ![image](https://user-images.githubusercontent.com/20179549/279038372-6ab7e0c4-45e4-469c-91f2-90284c35e610.png)

内核是 6.1 就是 6.1，没毛病啊（系统版本号是7

**Comment by ilharp** [comment]
> 内核是 6.1 就是 6.1，没毛病啊（系统版本号是7

那么你能理解 Windows 版本 10.0.22000 以上的版本号是 11 这件事吗？如果可以就可停止回复了。如果不可以的话，建议寻找对计算机比较懂的朋友为你讲解。我会讲上面的讨论标记为 OT。
