### ISSUE TITLE
Bug: `plugin-logger` 限制显示的行数

### ISSUE THREAD

**Issue by ilharp** [koishijs/webui#2]
### Describe the bug

`plugin-logger` 传递当日日志，不限制行数或大小。

### Steps to reproduce

在当日内产生很多日志，使得控制台无法加载。

### Expected behavior

`plugin-logger` 应该：

1. 只传递当日的日志。

1. 如果可能的话，使用不需要遍历文件的方法提取日志文件的最后 `500` 条消息。如果不可能，直接传递 `日志文件的大小已经超出限制。`

1. 得到字串后，检查字串长度是否超过 `500 * 200`。超过则直接传递 `日志文件的大小已经超出限制。`

**Comment by shigma** [comment]
新版本下此问题已经得到一定程度的解决：

1. logger 目前仅传递当次启动时的日志。
2. 任何情况下，初次登入控制台时接收到的日志总体积不会超过 100kB（由于分片机制可能仅会收到较少数据，可以之后改善）。此后日志会递增性积累，但不会很快达到让浏览器崩溃的程度。如果出现卡顿，手动刷新即可重新限制前端数据量。
3. 为日志界面引入了虚拟滚动以优化性能。

后续：

1. 如果觉得目前分片机制可能导致接收到数据太少，可以另行提交 issue（不属于本 issue 的范围）。
2. 如果希望引入翻页、无限滚动、历史查询相关功能，可以另行提交 issue（不属于本 issue 的范围）。
