### ISSUE TITLE
Feature: 加个 robot.txt 来配置开公网后是否允许搜索引擎爬虫爬

### ISSUE THREAD

**Issue by yi03** [koishijs/webui#205]
目前使用bing和google搜索某些关键词可以搜到很多开了公网且没有启用auth插件的实例，但是这些用户应该绝大多数都是不希望搜索引擎收录自己实例的网页的，所以不知道有没有可能加个 robot.txt 来配置开公网后是否允许搜索引擎爬虫爬，默认不允许爬。

**Comment by shigma** [comment]
可以做。有没有 robot.txt 用于参考？

**Comment by ilharp** [comment]
个人认为此功能应当由插件实现，推荐前往论坛的「[求插件](https://forum.koishi.xyz/c/plugin-request)」版块请求插件。不应由 webui 处理此行为。

**Comment by shigma** [comment]
> 个人认为此功能应当由插件实现，推荐前往论坛的「[求插件](https://forum.koishi.xyz/c/plugin-request)」版块请求插件。不应由 webui 处理此行为。

是应该由插件实现，但由于此功能可能需要内置于整合包中，所以还是需要由官方控制。

**Comment by ilharp** [comment]
我不认为该功能应当内置于整合包中。内置于整合包会增加整合包的体积，对于非常用和必要的功能应当由用户自行在插件市场中下载插件。

**Comment by yi03** [comment]
> 可以做。有没有 robot.txt 用于参考？

我之前打错了，应该是robots.txt。
写成这样可以禁止搜索引擎爬取网站的所有页面
```
User-agent: *
Disallow: /
```

**Comment by shigma** [comment]
已经实现：https://github.com/koishijs/koishi-plugin-public
