### ISSUE TITLE
Bug: `config`保存按钮无效

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/webui#209]
已经有不知道几个版本没见这按钮亮过了

**Comment by shigma** [comment]
你在说什么

**Comment by ilharp** [comment]
![image](https://github.com/koishijs/webui/assets/20179549/a3d2fd0a-bdca-417e-8063-57822ae52f00)

任何插件的保存配置按钮在首次访问时均不可用，刷新即可解决。

**Comment by Hieuzest** [comment]
看到楼上的回复想了想我还以为是 #89 
然后尝试了一下发现并不是

此问题说的是，如果这一个浏览器Session是从任何/config以外的path进入的（比如直接打开/），那么从侧边栏进入config后，除全局fullReload的Apply按钮以外，其余所有插件的保存按钮均不可用
如果在config页面刷新则解除此状态

**Comment by shigma** [comment]
看了一下还是不知道为什么。

起因是包含 config.save 的 action 被 dispose 掉了。因为包含该 action 的组件触发了 onBeforeUnmount 钩子。之所以只有这一个按钮出问题，是因为 config.save 被注册了两次，一次是在全局设置组件中，一次是在插件设置组件中。按理说这两个组件的关系是 v-if/v-else，只应该同时存在一个 action，并且一个被 unmount 后另一个应该 mount 才对。但实际情况确实，当从其他页面跳转到 config 页面时，全局设置都会被 unmount 一次，从而导致 action 失效，按钮变灰。

目前尚不清楚其中的原理，可能是 Vue 的某项机制所致。

暂时的解决办法：避免使用 v-if/v-else 注册两个 action，使用传引用的方式在入口文件中只实现一次该 action。
