### ISSUE TITLE
Feature: 浏览器端 Fetch 插件市场的插件列表和信息

### ISSUE THREAD

**Issue by idanran** [koishijs/webui#211]
经过 node 可能会导致以下问题：
```[W] market Error: getaddrinfo ENOTFOUND registry.koishi.chat```
![image](https://github.com/koishijs/webui/assets/96647698/d95e4505-2caa-41ab-b3c5-76f0be394686)

类比：https://koishi.chat/zh-CN/market/

**Comment by ilharp** [comment]
如果 Node 侧出现了问题，那么在 Node 侧解决此问题即可。为绕过问题而重写整个插件的逻辑的成本要大于解决此问题的成本。

此外，就此问题而言，使用浏览器进行插件市场信息的获取同样会失败，因为这需要服务端进行 CORS 的配置。如果用户使用镜像，那么镜像端也需要进行同样的配置，这会大大增加插件市场服务端和镜像的配置和维护成本，从而使这一方案的可行性降低。

**Comment by idanran** [comment]
> 如果 Node 侧出现了问题，那么在 Node 侧解决此问题即可。为绕过问题而重写整个插件的逻辑的成本要大于解决此问题的成本。
> 
> 此外，就此问题而言，使用浏览器进行插件市场信息的获取同样会失败，因为这需要服务端进行 CORS 的配置。如果用户使用镜像，那么镜像端也需要进行同样的配置，这会大大增加插件市场服务端和镜像的配置和维护成本，从而使这一方案的可行性降低。
> 

确实

**Comment by shigma** [comment]
1. 新用户每次访问会造成插件市场服务器压力大幅增加；如果把缓存逻辑放在后端就变成 node 侧的当前实现了
2. 考虑到插件市场镜像服务可能不支持浏览器端访问，把访问限制在浏览器会降低用户选择镜像的可用性

**Comment by idanran** [comment]
> 1. 新用户每次访问会造成插件市场服务器压力大幅增加；如果把缓存逻辑放在后端就变成 node 侧的当前实现了
> 2. 考虑到插件市场镜像服务可能不支持浏览器端访问，把访问限制在浏览器会降低用户选择镜像的可用性

目前似乎会把错误页面缓存下来。

**Comment by ilharp** [comment]
> 目前似乎会把错误页面缓存下来。

点击右上角刷新按钮即可。

**Comment by idanran** [comment]
> > 目前似乎会把错误页面缓存下来。
> 
> 点击右上角刷新按钮即可。

点了没反应 #198

**Comment by shigma** [comment]
点了没反应就等待对应 issue 被处理，而不是提出错误的解决方案。
