### ISSUE TITLE
插件给命令配置页面 增加 schema 之后 卸载插件不会移除

### ISSUE THREAD

**Issue by 502647092** [koishijs/webui#215]
多次重载 会导致生成多个配置项

这个是代码
![image](https://github.com/koishijs/webui/assets/10203793/fb3cbf0b-9874-4f77-9908-13d6869a6286)
这个是重复生成的页面
![image](https://github.com/koishijs/webui/assets/10203793/4c2b042f-5044-48ed-abb4-49a868092370)

**Comment by shigma** [comment]
已成功复现此问题，将尽快修复。
