### ISSUE TITLE
Bug: 有关 plugin-analytics 在 koishi 4.x 的一些异常情况

### ISSUE THREAD

**Issue by dragon-fish** [koishijs/webui#221]
### Describe the bug

控制台 Analytics 图表中可能会出现一些异常的超大数字

![image](https://github.com/koishijs/koishi/assets/44761872/e651429a-4bbe-413f-bc2f-39c986e0a17c)

以及没有数字

![image](https://github.com/koishijs/koishi/assets/44761872/345d3e10-e0f0-4a7e-844e-82cdebe9835b)

### Steps to reproduce

具体触发原理尚不明确

可能与使用 MongoDB 有关

### Expected behavior

数据正常

### Versions

![77038b3ace039fc55ea9319236f9027b](https://github.com/koishijs/koishi/assets/44761872/b2c467f4-b927-4b61-8ba1-d19df0fb011b)

**Comment by shigma** [comment]
最新版本应该修复了此问题。
