### ISSUE TITLE
Feature: status插件在bot名前加上平台名

### ISSUE THREAD

**Issue by itzdrli** [koishijs/webui#236]
![image](https://github.com/koishijs/webui/assets/52338732/c4e88345-6944-45a2-9d0a-5ebf793dd8d9)
这是现在的status信息，在bot多平台名字大致相同的情况下根本分不清哪个是哪个，
希望能在bot的名字前加上平台
比如这样:
```
Discord: Fantastic Spoon：运行中
Telegram: FantasticSpoonBot：运行中
==========
CPU 使用率：0% / 1%
内存使用率：5% / 49%
```

**Comment by itzdrli** [comment]
> 改 i18n 应该可以

试过，没改明白

**Comment by shigma** [comment]
改 i18n 确实可以，不过我还是应该内置一下。提议不错。
