### ISSUE TITLE
Feature: status 插件的状态栏显示的机器人信息 点击跳转对应适配器配置

### ISSUE THREAD

**Issue by 502647092** [koishijs/webui#238]
status 插件的状态栏显示的机器人信息 点击跳转对应适配器配置
![image](https://github.com/koishijs/webui/assets/10203793/91030824-c180-41b1-b00c-444be3a1d6b1)
比如点击头像 跳转到对应的适配器插件页面

**Comment by CyanChanges** [comment]
根据 bot 实例拿插件配置路径似乎有一些麻烦？（
