### ISSUE TITLE
Feature: Service dependencies mismatch warnings between "package.json" and cordis "using"

### ISSUE THREAD

**Issue by TimeBather** [koishijs/webui#241]
### Describe the problem related to the feature request

自从Cordis 2.11，在插件中访问没有在"using"字段中定义的依赖会产生一个警告。我认为有必要检查package.json和"using"字段中定义的依赖的一致性，因为Koishi插件管理器会读取和展示package.json中的以来信息并在控制台展示，这对于使用插件的人来说很重要。

Since Cordis 2.11, access the dependencies which did not declared in the "using" field of the plugin will cause a warning. I think it's nesseary to check the consistency between the package.json and "using" field because the koishi plugin manager reads and displays them in the console page. It's important for user who using these plugins.

### Describe the solution you'd like

无
None

### Describe alternatives you've considered

无
None

### Additional context

无
None

**Comment by shigma** [comment]
咦，我刚刚想到，现在可以声明 required 和 optional 的话，是不是没有必要在 package.json 中声明服务依赖了？

**Comment by MaikoTan** [comment]
> 咦，我刚刚想到，现在可以声明 required 和 optional 的话，是不是没有必要在 package.json 中声明服务依赖了？

I think it should be still required, since you don't have approaches to get the `inject.required` and `inject.optional` before installing a plugin.

我認爲它依舊是必要的，因爲在安裝插件之前你並沒有方法得到 `inject.required` 和 `inject.optional`

**Comment by shigma** [comment]
安装插件之前也不需要这些数据吧……
