### ISSUE TITLE
Feature: 插件配置项 object array 类型支持表格视图

### ISSUE THREAD

**Issue by maxoyed** [koishijs/webui#242]
目前对象数组类型在 console 配置页面只能以列表样式展示，如果数组元素过多会出现页面过长的情况，不方便编辑。希望可以为对象数组类型增加表格视图支持。

**Comment by shigma** [comment]
官方文档已经有支持表格的例子了，请指出与官网示例的区别。

**Comment by maxoyed** [comment]
> 官方文档已经有支持表格的例子了，请指出与官网示例的区别。

官网示例是string[]，这个确实可以，但是object[]不行；比如这样一个结构：
```typescript
{
    name: string;
    id: number;
}[]
```

我希望在配置页直接显示成表格，表头是name和id，测试了一下，目前好像不支持

**Comment by shigma** [comment]
![image](https://github.com/koishijs/webui/assets/33423008/312c4002-ad7e-4edc-a2b5-1af5ec83ab00)

这种算不算？

**Comment by maxoyed** [comment]
> ![image](https://user-images.githubusercontent.com/33423008/280508603-312c4002-ad7e-4edc-a2b5-1af5ec83ab00.png)
> 
> 这种算不算？

这种是dict，我提到那种和目前控制台直接编辑数据库的视图应该是差不多的

![image](https://github.com/koishijs/webui/assets/25519245/417aaf86-b374-4791-bdc7-67ceb4f98264)

表头是 Key Name，每一行是一个 Array 的 element，最后得到的结构类似这种：

```typescript
[
  {
    id: 1,
    uid: 7,
    month: 11,
    day: 5
  },
  {
    id: 2,
    uid: 8,
    month: 12,
    day: 6
  },
]
```

**Comment by shigma** [comment]
> 这种是dict，我提到那种和目前控制台直接编辑数据库的视图应该是差不多的

array 也支持啊……你试过没有

**Comment by maxoyed** [comment]
> > 这种是dict，我提到那种和目前控制台直接编辑数据库的视图应该是差不多的
> 
> array 也支持啊……你试过没有

新开了一个测试，确实有，可能是我配置联动的时候出问题了，我再检查一下

**Comment by maxoyed** [comment]
配置联动没弄好，table视图没问题，OK了
