### ISSUE TITLE
Feature：支持从插件市场批量安装插件

### ISSUE THREAD

**Issue by shigma** [koishijs/webui#254]
在导航栏增加一个「多选」按钮，点击后进入多选模式。

在多选模式下，插件的「安装」按钮将变为 checkbox，勾选后将添加到「依赖管理」页面中，且可以取消勾选。勾选完成后点击导航栏的「安装」按钮将直接对已经勾选的全部插件进行安装；也可以到「依赖管理」页面中进行安装。

相关问题：https://github.com/koishijs/webui/issues/58

**Comment by 502647092** [comment]
感觉可以加一个任务队列 支持 删除 更新 安装 最后点击执行
