### ISSUE TITLE
bug: 全局配置 prefix 添加分支 在 dev 环境下 报错

### ISSUE THREAD

**Issue by 502647092** [koishijs/webui#256]
![image](https://github.com/koishijs/webui/assets/10203793/519522af-fbde-4215-87bf-8a1daf1c6272)
点击添加分支时 报错

**Comment by shigma** [comment]
related：https://github.com/koishijs/koishi/issues/1261

**Comment by shigma** [comment]
已修复，将于下个版本实装。
