### ISSUE TITLE
Feature request: 消除警告 The --registry option is deprecated; prefer setting npmRegistryServer in your .yarnrc.yml file

### ISSUE THREAD

**Issue by idanran** [koishijs/webui#257]
@koishijs/plugin-market: 2.5.0

**Comment by ilharp** [comment]
这是预期行为，不是一个 bug。此行为自 Yarn Berry 发布以来已经存在 2 年，并未影响任何人的需求。

未来 market 插件可能会取消使用 `--registry` 以使 Yarn 使用 `.yarnrc.yml`，但不意味着现有行为是 bug。可以考虑修改为 Feature Request。

**Comment by idanran** [comment]
> 这是预期行为，不是一个 bug。此行为自 Yarn Berry 发布以来已经存在 2 年，并未影响任何人的需求。
> 
> 未来 market 插件可能会取消使用 `--registry` 以使 Yarn 使用 `.yarnrc.yml`，但不意味着现有行为是 bug。可以考虑修改为 Feature Request。
> 

已修改

**Comment by shigma** [comment]
> 未来 market 插件可能会取消使用 `--registry` 以使 Yarn 使用 `.yarnrc.yml`，但不意味着现有行为是 bug。可以考虑修改为 Feature Request。

这是否意味着去掉这个配置项？不然就得写入 `.yarnrc.yml` 了。
