### ISSUE TITLE
bug: plugin-commands 页面选择指令报错

### ISSUE THREAD

**Issue by 502647092** [koishijs/webui#258]
![image](https://github.com/koishijs/webui/assets/10203793/36648dc6-f0b5-431c-bcab-f4012dde1227)
怎么触发的暂时未知 但是看了看代码 是这里的 schema 为 undefined 导致的
https://github.com/koishijs/webui/blob/816d95c9bc8568c00508741e96138a4049ef5c10/plugins/commands/client/utils.ts#L20-L31

**Comment by shigma** [comment]
我为什么没有复现……

1. 请尝试最新版本能否出现错误
2. 请尝试刷新页面能否解决问题

**Comment by 502647092** [comment]
这是 4.15.6 版本出现的问题
而且刷新无法解决
具体怎么触发的 不知道
我现在已经更新最新版了
好像没出现这个问题

**Comment by shigma** [comment]
好的，那我先关闭，如果仍然出现可以继续回复。

**Comment by 502647092** [comment]
目前已复现 复现方式
在 external 目录 通过软连接 放置一个插件
```
root@debian:/development/koishi-app/external# ls -al
total 4
drwxr-xr-x  2 root root   29 Dec 20 10:08 .
drwxr-xr-x 11 root root 4096 Dec 20 09:24 ..
lrwxrwxrwx  1 root root   41 Dec 20 10:08 miao-permission -> ../../koishi-dev/external/miao-permission
```
并且插件中有涉及 command 的 schema 的代码
```
    ctx.schema.extend('command', Schema.object({
      showWarning: Schema.boolean().description('警告信息是否提示用户。'),
    }), 900)
    ctx.schema.extend('command', Schema.object({
      permission: Schema.string().experimental().description('命令权限。'),
    }), 900)
```
启动之后 会导致此问题

**Comment by shigma** [comment]
这可能是因为你的 Schema 多例导致。请确保 Koishi 使用的 Schema 和你扩展中使用的 Schema 是同一个，后再次复现。

**Comment by 502647092** [comment]
@shigma 怎么判断是否多例了 理论上有软连接的情况下 应该可以正常运行吧

**Comment by shigma** [comment]
> 怎么判断是否多例了

`Schema.object()` 的 `Schema` 不是同一个对象，可能会导致错误。

> 理论上有软连接的情况下 应该可以正常运行吧

Koishi 模板项目大量使用软链接技术，且能够正常运行。软链接不影响运行的前提是你的操作方式能够正确解析依赖。

我目前在任何情况下都没有复现你的问题，所以作此猜测。如果你能提供一个从模板项目起的完整复现流程，我可以进一步研究。

**Comment by shigma** [comment]
确实是多例问题。

如果你需要两种启动方案，可以直接准备两个 koishi.yml，然后使用 `yarn start koishi-1.yaml` 启动。

如果你现在有两个开发环境，建议合并为一个。两个开发环境存在的巨大问题在官方文档中已经介绍。

如果你需要专门的生产环境，那么需要强调生产环境应当有固定的 lockfile，故不应当使用 link。你应当发布后下载。
