### ISSUE TITLE
Bug: 当安装插件时 package.json 添加成功 但是 安装失败时 无法再次安装

### ISSUE THREAD

**Issue by 502647092** [koishijs/webui#271]
![6d3a30f7c855d432d7aae5dddff88640](https://github.com/koishijs/webui/assets/10203793/544d4149-9620-41b2-bad9-67a150e6a76e)
![25a86993af875dc5d005bf0b7bb968e9](https://github.com/koishijs/webui/assets/10203793/68684dcf-0a86-42ff-b661-2602d7aefcfc)

**Comment by shigma** [comment]
目前无法安装的问题暂时得到解决，但是重新安装后仍然需要一次重启才能看到依赖。

可以视为 #265 的 duplicate。
