### ISSUE TITLE
[plugin-console] Error: Cannot find module 'unocss/preset-mini'

### ISSUE THREAD

**Issue by maxoyed** [koishijs/webui#283]
https://github.com/koishijs/webui/blob/8a93765c255e3215913295e2e29ad07ce907fab7/plugins/console/src/node/index.ts#L169-L170

应该改为 `@unocss/preset-mini` 和 `@unocss/vite`

**Comment by shigma** [comment]
应该是缺依赖导致的，最新版已经修了。
