### ISSUE TITLE
Feature: 增加重置按钮

### ISSUE THREAD

**Issue by Kabuda-czh** [koishijs/webui#297]
### Describe the problem related to the feature request

在插件自身的配置页面中, 增加重置功能方便于重新配置数据, 以及解决可能的冲突问题

### Describe the solution you'd like

增加重置按钮, 以及点击需要用户进行二步确认防止误触

**Comment by shigma** [comment]
然而目前的配置页面，只要点到其他插件再点回来，配置就没了。所以是不是不需要这个按钮了？
