### ISSUE TITLE
Feature: 添加启用/禁用指令 alias 功能

### ISSUE THREAD

**Issue by Seidko** [koishijs/webui#298]
### Describe the problem related to the feature request

为 commands 插件添加启用/禁用指令 shortcut 功能。

### Describe the solution you'd like

为 commands 插件添加启用/禁用指令 shortcut 功能。

**Comment by shigma** [comment]
更新：shortcut 功能现在已经废弃，推荐使用 alias。因此这个 issue 将用于讨论「添加启用/禁用指令 alias 功能」。
