### ISSUE TITLE
指令管理菜单消失

### ISSUE THREAD

**Issue by Neptune1990** [koishijs/webui#322]
![image](https://github.com/koishijs/webui/assets/107494041/e33c1603-9fdd-4a9d-807c-92f1e7e28082)
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700

Binaries:
    Node: 20.3.1
    Yarn: 4.0.1

Koishi:
    Core: 4.17.3
    Console: 5.26.6
    Koishi Desktop: 1.0.0

**Comment by shigma** [comment]
你的配置文件出现了异常。请尝试删除这个配置（不是删除插件），然后重新添加插件配置。

**Comment by Neptune1990** [comment]
已解决
