### ISSUE TITLE
@koishijs/console@5.30.0 似乎在生产模式下的数组配置项 展示不符合预期

### ISSUE THREAD

**Issue by shangxueink** [koishijs/webui#337]
---

详见

https://github.com/koishijs/koishi/issues/1474#issuecomment-2453056156

（因为在那边提了issue但是意识到了似乎是console依赖的问题，所以又到这里了

---

**Comment by qwqmengmeng** [comment]
喵～

**Comment by shangxueink** [comment]
喵~~

**Comment by qwqmengmeng** [comment]
喵~

**Comment by shangxueink** [comment]
好像不是 @koishijs/console ，是 plugin 的那个~
