### ISSUE TITLE
Bug: `logger` 大量日志由于同步问题不会写入文件

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/webui#338]
https://github.com/koishijs/webui/blob/c05c426ecac621b5930ea35e66ca8731cb5c397c/plugins/logger/src/file.ts#L22-L32

此处 await 后 temp 可能发生改变，导致大量日志被丢弃未能写入文件

**Comment by shigma** [comment]
Fixed by https://github.com/koishijs/webui/pull/339
