### ISSUE TITLE
bug: 处理日志文件占用过多的内存

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/webui#50]
由于某些插件未保持更新或存在问题，导致部分用户日志文件中存在大量报错信息。当日志文件过大（复现日志 30M），koishi 启动时会占用过量内存导致 OOM 报错并自动循环重启。

复现流程：
- 运行 yarn create koishi 创建一个新的项目
- 把日志填充至 50MB
- 启动 koishi

![UN~}14S(`R1UOTB~W7PI0E2](https://user-images.githubusercontent.com/37006258/205453148-ade69794-9979-4ec2-b33a-b3feb87c8520.jpg)

![%5DTPV~3`YK _VRY 9U9KK5](https://user-images.githubusercontent.com/37006258/205453172-1f060b60-ff41-483b-85f2-9436f5a091bb.jpg)

**Comment by shigma** [comment]
已确认此问题，后续会解决。

**Comment by MirrorCY** [comment]
临时解决方案，删除所有日志后重启 Koishi
