### ISSUE TITLE
Bug: page freezes or crashes when searching in the plugin market

### ISSUE THREAD

**Issue by shigma** [koishijs/webui#55]

**Comment by shigma** [comment]
已确定卡死问题只与 `devMode` 相关，在生产环境下搜索功能丝般顺滑。

**Comment by shigma** [comment]
此问题疑似不仅限于插件市场，但是在插件市场页面中尤为明显。很可能涉及 Vue 的优化。

**Comment by MaikoTan** [comment]
I'll take a look if you don't.
Performance optimisation is a complicated problem as always.
