### ISSUE TITLE
Bug: 打开日志页并没有自动滚动到底部

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/webui#63]
目前打开日志页仍然不能自动滚到底部

a475bf8 将 wrapper 改为 root.parentElement.parentElement 经过测试可以滚动
![image](https://user-images.githubusercontent.com/21092951/210173186-79b60407-4b76-4895-b593-7c8535b53a07.png)
![image](https://user-images.githubusercontent.com/21092951/210173430-75d9dce8-2123-4a4a-b00c-a0d172d2fcfd.png)

**Comment by shigma** [comment]
Thanks. Willing to open a PR for that?

**Comment by H4M5TER** [comment]
I didn't fix it.
Tried to do the same that changed code do and it actually scrolled.
So I was wondering why it isn't work currently.
