### ISSUE TITLE
Bug: status bar multiple copies

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/webui#89]
### Describe the bug

Updating the console plugin will cause the status bar to display multiple copies, restarting koishi can resolve this issue.

F5 also resolve that.

### Steps to reproduce

1. Keep all plugins up to date
2. Downgrade console to 5.1.10
3. Upgrade console to 5.1.14

### Expected behavior

After the update, no wrong display appears.

### Screenshots

![image](https://user-images.githubusercontent.com/37006258/213807512-181d1966-ac22-4336-b7c0-11b3ce1b6df3.png)

### Versions

- Koishi version: 4.11.2

**Comment by ilharp** [comment]
![image](https://user-images.githubusercontent.com/20179549/230533129-0ba188c3-c40e-42da-8551-c731149fce0d.png)

确认是在 Koishi 本体 Full Reload 而 webui 未刷新的情况下会出现。

**Comment by Hieuzest** [comment]
此问题在每次打开一个新的Console网页后reload任何console插件时稳定复现（即unload时没有清除），且仅在对每个插件的第一次reload时有效。

**Comment by shigma** [comment]
https://github.com/koishijs/webui/blob/9589e1afafb8e165ba1c7d8082e8536ff2027ff7/packages/client/client/loader.ts#L74

非常奇怪，我明明写了清除的逻辑。

而且只有 prod 可以复现，导致很难调试。

**Comment by shigma** [comment]
这个问题目前是不是没了……

**Comment by MirrorCY** [comment]
Hmm... 最近没听说有这个问题，感觉可以直接关了（

**Comment by shigma** [comment]
OK 可能之前修过，以后如果遇到问题再说吧。

**Comment by MirrorCY** [comment]
用户群反馈此问题已经数月未复现，可以关闭。
如果再次出现请打开它
